# Generated by Django 4.0.4 on 2022-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='price',
            field=models.IntegerField(),
        ),
    ]
