# Generated by Django 4.0.4 on 2022-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_brand_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
    ]
