# Generated by Django 4.0.4 on 2022-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_brand_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
