# Generated by Django 4.0.4 on 2022-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_phone_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='phones/'),
        ),
    ]
